ServitecWeb/Servitec/Servitec/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from apps.vistas import views
from django.contrib.auth.views import LoginView 
from apps.frontend.api import urls
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static
from django.conf import settings
admin.autodiscover()
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    #url('',include('apps.vistas.urls',namespace='vistas')),
    url('usuario/',include('apps.usersDivision.urls')), 
    #url('',LoginView.as_view(template_name='login.html'),name='login_usuario'), 
    path('rest-auth/', (include('rest_auth.urls'))),
    #url(r'^login/',LoginView.as_view(template_name='login.html'),name='login_usuario'), 
    path('api-auth/', include('rest_framework.urls')),
    path('api/',include('apps.frontend.api.urls')),
    path('api-autent/', include('apps.usersDivision.api.urls')),
    path('rest-auth/registration',include('rest_auth.registration.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ServitecWeb/Servitec/apps/vistas/urls.py
from django.conf.urls import url, include
from apps.vistas import views
from apps.frontend import views as frontviews
app_name="vistas"
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^nosotros/$',views.nosotros,name='nosotros'),
    url(r'^trabajos/$',views.trabajos,name='trabajos'),
    url(r'^consejosLadrillos/$',views.consejos,name='consejosLadrillos'),
    url(r'^creadores/$',views.creadores,name='creadores'),
    url(r'^contactos/$',views.contactos,name='contactos'),
    url(r'^api/trabajo/$', frontviews.trabajo_list),
    url(r'^api/trabajo/(?P<pk>[0-9]+)$', frontviews.trabajos_detail),
   
]

ServitecWeb/Servitec/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block extrahead %}
	{% endblock %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/estilos2.css' %}" rel="stylesheet" type="text/css">
	<meta charset="UTF-8">
	<title>{% block title %}Servitec{% endblock %}</title>
</head>
<body>
	<div class="container-fluid">
		{% block navbar %}
		<div class="row sticky-top">
        <nav id="encabezado" class="navbar navbar-expand-sm navbar-dark col-md-12">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menuPrincipal">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="row col-md-4">
            <figure id="logo" class="d-none d-md-block">
                <a href="{% url 'vistas:index' %}"><img src="{% static 'img/logo.png' %}" alt="Image Not Found"></a>
            </figure>
          </div>
          <div id="menuPrincipal" class="collapse navbar-collapse col-md-8">
              <ul id="menu" class="list-inline navbar-nav mx-auto ">
                <li class="list-inline-item nav-item"><a class="nav-link" href="{% url 'vistas:index' %}">Inicio</a></li>
                <li class="list-inline-item nav-item "><a class="nav-link" href="{% url 'vistas:nosotros' %}">Nosotros</a></li>
                <li class="list-inline-item nav-item "><a class="nav-link" href="{% url 'vistas:trabajos' %}">Trabajos</a></li>
                <li class="list-inline-item nav-item "><a class="nav-link" href="{% url 'vistas:consejosLadrillos' %}">Consejos</a></li>
                <li class="list-inline-item nav-item "><a class="nav-link" href="{% url 'vistas:creadores' %}">Creadores</a></li>
                <li class="list-inline-item nav-item "><a class="nav-link" href="{% url 'vistas:contactos' %}">Contáctenos</a></li>
              </ul>
		<div class="row col-md-1" id="login">
              <form action="{% url 'login_usuario' %}" method="post" class="form-inline my-2 my-lg-0">
                {% csrf_token %}
                <button class="btn btn-secondary" type="submit">Login</button>
            </form>
          </div>
            </form>
            </div>
        </nav>
      </div>
		{% endblock %}

		{% block content %}
			<h5>Este es el contenido del archivo base</h5>
		{% endblock %}

		{% block footer %}
		<div class="row">
        	<footer id="footPaginas" class="col-xl-12">
        	</footer>
      	</div>
		{% endblock %}
	</div>
	{% block extrajs %}
	{% endblock %}
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	
</body>
</html>